### ISSUE TITLE
Found error message in function sqlInjection

### ISSUE THREAD

**Issue by forsiam** [RisingStack/protect#6]
I use node v4.1.2,  I found this error 

D:\website\server\ws\node_modules\@risingstack\protect\lib\express\index.js:21
function sqlInjection (options = {}) {
                               ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\website\server\ws\node_modules\@rising
stack\protect\lib\index.js:3:17)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

how to solve this problem? thank a lot

**Comment by tothandras** [comment]
Same as #3.
